[package]
name = "minecraft-protocol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytebuffer = "2.2.0"
tokio = {version = "1.37.0", features = ["full"]}
